print("=== NHẬP THÔNG TIN NHÂN KHẨU HỌC ===")
ho_ten = input("Họ và tên: ")
tuoi = int(input("Tuổi: "))
gioi_tinh = input("Giới tính (Nam/Nữ): ")
hon_nhan = input("Tình trạng hôn nhân: ")
print("\n=== THÔNG TIN NHẬP VÀO ===")
print("Họ và tên:", ho_ten)
print("Tuổi:", tuoi)
print("Giới tính:", gioi_tinh)
print("Tình trạng hôn nhân:", hon_nhan)
